[package]
name = "libfuzzer"
version = "0.1.0"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
afl = { path = "../../afl/" }

[lib]
crate-type = ["staticlib", "cdylib"]

[profile.release]
lto = true
opt-level = 3

